services:
  - type: web
    name: credit-card-optimizer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: USE_CACHE
        value: true
      - key: OFFLINE_MODE
        value: false
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        sync: false

