services:
  - type: web
    name: credit-card-optimizer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: export PYTHONPATH=/opt/render/project/src:$PYTHONPATH && cd /opt/render/project/src && python -m uvicorn credit_card_optimizer.api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: USE_CACHE
        value: true
      - key: OFFLINE_MODE
        value: false
      - key: PYTHONUNBUFFERED
        value: "1"

