services:
  - type: web
    name: credit-card-optimizer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: export PYTHONPATH=/opt/render/project/src:$PYTHONPATH && python credit_card_optimizer/main.py
    envVars:
      - key: USE_CACHE
        value: true
      - key: OFFLINE_MODE
        value: false
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PORT
        sync: false

